# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "tot"
client_id = "dfdfdee5df77555148da4081a253b2f6"
application_url = "https://veteran-headquarters-basketball-fs.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_script_tags,read_script_tags,read_orders"

[auth]
redirect_urls = [
  "https://veteran-headquarters-basketball-fs.trycloudflare.com/auth/callback",
  "https://veteran-headquarters-basketball-fs.trycloudflare.com/auth/shopify/callback",
  "https://veteran-headquarters-basketball-fs.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "token-of-trust.myshopify.com"
